### ISSUE TITLE
Run the code without a bundler?

### ISSUE THREAD

**Issue by mesa123123** [PacktPublishing/Game-Development-with-Rust-and-WebAssembly#17]
Is there anyway to work through this guide without a bundler?
I believe webpack is getting in the way of me being able to complete this boook sadly :(

**Comment by paytonrules** [comment]
Hmmm, I'm not sure - what trouble is bundler giving you, do you have an error message?

Also if you want you can track me down directly you can find me in the Rustacean Station Discord (https://discord.gg/p5j43sjd) - invite will expire in 7 days.

**Comment by mesa123123** [comment]
Yes you were right! I ended up destroying my code in order to reclone the repo from the release I was on for the chapter but I basically got it working! Its a shame considering I accidentally deleted what I had already written so I couldn't figure out what I'd been working on! Thanks for the invite to the discord though I'll post there to see if anyone can tell me the cause of the issue
